language: js

before_install:
  - npm install -g npm@5.5.1

before_script:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt
  - npm test
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: required
addons:
  chrome: stable

deploy:
  provider: releases
  file: pulsar-date-picker.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
